# Generated by Django 4.0.3 on 2022-03-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_content_remove_article_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Diary',
        ),
    ]
